### ISSUE TITLE
在使用HEE的冒险家日志时，游戏崩溃

### ISSUE THREAD

**Issue by Omgise** [xiaoxing2005/BetterTooltipBox#3]
@xiaoxing2005 在按冒险家日志的翻页键时崩溃

https://github.com/user-attachments/assets/7fc5c00d-b8e5-4be1-ba1e-956470cf69f0

[crash-2024-08-18_16.36.53-client.txt](https://github.com/user-attachments/files/16647707/crash-2024-08-18_16.36.53-client.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/16647708/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/user-attachments/files/16647709/fml-junk-earlystartup.log)
[latest.log](https://github.com/user-attachments/files/16647710/latest.log)
[LootGames.log](https://github.com/user-attachments/files/16647711/LootGames.log)

**Comment by Omgise** [comment]
我在日志里发现了BetterTooltipBox的Mixin
```
	Mixins in Stacktrace: 
		net.minecraft.client.gui.GuiScreen:
			mixins.BetterTooltipBox.json:TooltipMixin from mod BetterTooltipBox
			mixins.ingameime.json:MixinGuiScreen from mod ingameime
			mixins.AppleCore.early.json:minecraft.GuiScreenMixin from mod AppleCore
		net.minecraft.client.Minecraft:
			mixins.hodgepodge.early.json:minecraft.profiler.MinecraftMixin from mod hodgepodge
			mixins.notfine.early.json:mcpatcherforge.base.MixinMinecraft from mod notfine
			mixins.archaicfix.early.json:client.core.MixinMinecraft from mod archaicfix
			mixins.hodgepodge.early.json:minecraft.MixinMinecraft_UnfocusedFullscreen from mod hodgepodge
			mixins.mkb.json:MixinMinecraft from mod mkb
			mixins.hodgepodge.early.json:minecraft.MixinMinecraft_ToggleDebugMessage from mod hodgepodge
			coretweaks.mixin.json:tweak.crashhandler.MixinMinecraft from mod coretweaks
			mixins.hodgepodge.early.json:minecraft.MixinMinecraft_UpdateKeys from mod hodgepodge
			mixins.modernsplash.json:MinecraftMixin from mod modernsplash
			mixins.falsetweaks.json:client.profiler.MinecraftMixin from mod falsetweaks
			mixins.lumi.json:client.MinecraftMixin from mod lumi
			mixins.flyingcullers.json:MixinMinecraft from mod flyingcullers
			mixins.hodgepodge.early.json:minecraft.MixinMinecraft_FastBlockPlacing from mod hodgepodge
			mixins.ingameime.json:MixinMinecraft from mod ingameime
			mixins.hodgepodge.early.json:minecraft.MixinMinecraft_ResizableFullscreen from mod hodgepodge
			mixins.hodgepodge.early.json:minecraft.MixinMinecraft_FixDuplicateSounds from mod hodgepodge
```

**Comment by xiaoxing2005** [comment]
调用链中并没有提及BetterTooltipBox的mixin，这里只是把所有的mixin给列了出来

> 我在日志里发现了BetterTooltipBox的Mixin
> 
> ```
> 	Mixins in Stacktrace: 
> 		net.minecraft.client.gui.GuiScreen:
> 			mixins.BetterTooltipBox.json:TooltipMixin from mod BetterTooltipBox
> 			mixins.ingameime.json:MixinGuiScreen from mod ingameime
> 			mixins.AppleCore.early.json:minecraft.GuiScreenMixin from mod AppleCore
> 		net.minecraft.client.Minecraft:
> 			mixins.hodgepodge.early.json:minecraft.profiler.MinecraftMixin from mod hodgepodge
> 			mixins.notfine.early.json:mcpatcherforge.base.MixinMinecraft from mod notfine
> 			mixins.archaicfix.early.json:client.core.MixinMinecraft from mod archaicfix
> 			mixins.hodgepodge.early.json:minecraft.MixinMinecraft_UnfocusedFullscreen from mod hodgepodge
> 			mixins.mkb.json:MixinMinecraft from mod mkb
> 			mixins.hodgepodge.early.json:minecraft.MixinMinecraft_ToggleDebugMessage from mod hodgepodge
> 			coretweaks.mixin.json:tweak.crashhandler.MixinMinecraft from mod coretweaks
> 			mixins.hodgepodge.early.json:minecraft.MixinMinecraft_UpdateKeys from mod hodgepodge
> 			mixins.modernsplash.json:MinecraftMixin from mod modernsplash
> 			mixins.falsetweaks.json:client.profiler.MinecraftMixin from mod falsetweaks
> 			mixins.lumi.json:client.MinecraftMixin from mod lumi
> 			mixins.flyingcullers.json:MixinMinecraft from mod flyingcullers
> 			mixins.hodgepodge.early.json:minecraft.MixinMinecraft_FastBlockPlacing from mod hodgepodge
> 			mixins.ingameime.json:MixinMinecraft from mod ingameime
> 			mixins.hodgepodge.early.json:minecraft.MixinMinecraft_ResizableFullscreen from mod hodgepodge
> 			mixins.hodgepodge.early.json:minecraft.MixinMinecraft_FixDuplicateSounds from mod hodgepodge
> ```

**Comment by Omgise** [comment]
那可能是HEE本身的问题？

**Comment by Omgise** [comment]
刚刚把BetterTooltipBox移除后再试了一下，确实不是BetterTooltipBox的问题，我得去GNTH开一个Issues了（
