### ISSUE TITLE
和NotEnoughItems还有CodeChickenCore不兼容

### ISSUE THREAD

**Issue by Omgise** [xiaoxing2005/BetterTooltipBox#4]
请看：https://github.com/GTNewHorizons/NotEnoughItems/issues/556

**Comment by Omgise** [comment]
@xiaoxing2005

**Comment by xiaoxing2005** [comment]
@Omgise 冲突已修复，关于nei缩放问题请安装angelica

**Comment by xiaoxing2005** [comment]
在不安装angelica的情况下nei的物品缩放功能就会出现你那个issue的问题

**Comment by Omgise** [comment]
感谢大佬！
