### ISSUE TITLE
在better questing任务书里提示框材质失效

### ISSUE THREAD

**Issue by haobawobufu** [xiaoxing2005/BetterTooltipBox#5]
如题，版本是GTNH2.7.0，在nei界面是正常加载的，但是在任务书内材质失效，请问能添加对better questing的支持吗？

**Comment by CanntReport** [comment]
> 如题，版本是GTNH2.7.0，在nei界面是正常加载的，但是在任务书内材质失效，请问能添加对better questing的支持吗？

任务书中的界面有单独的材质配置，推荐自己修改

**Comment by haobawobufu** [comment]
还有一个小问题，当前270版本（java20）使用后并没有炫彩选择框的效果，还是原版的黑线，我看代码里是支持的

**Comment by CanntReport** [comment]
> 还有一个小问题，当前270版本（java20）使用后并没有炫彩选择框的效果，还是原版的黑线，我看代码里是支持的

关于我的上一个回答，我删掉它的原因是，经过我的测试后，发现并不是那个材质。
我寻找更改材质的方法是因为我看不清任务书中的暗蓝色字体，最后我放弃修改材质，而是手动修改了任务书的部分字体（§1->§2，§l->删除)。

关于炫彩选择框的问题，我在GTNH2.7.0中使用Java21，光影为ComplementaryShaders_v4.5.1，炫彩选择框可以正常生效。

![image](https://github.com/user-attachments/assets/9d608084-cb21-44fd-be8c-d8bde2f6fcec)

如果是在问另一个选择框的话，我这里是这样的

![image](https://github.com/user-attachments/assets/4051cb8a-b15e-406f-83d4-5905471fc5e6)

**Comment by haobawobufu** [comment]
Complementary光影应该是自带炫彩选择框的，我看到mod里面有添加炫彩选择框的函数，以为mod里的炫彩选择框不需要开光影就能用。
任务书里的提示框指的是任务书里面的物品的提示框，还是原版的，并没有替换成mod里的材质，如下图，其实图里面一些深色字体显示效果确实不太好，所以确实是没办法改这个提示框材质是吗
![4d4bd9ee0fcc2cec49c894d92cb2bc36](https://github.com/user-attachments/assets/88617b97-51cc-4541-b620-7c89d092c386)

**Comment by CanntReport** [comment]
> Complementary光影应该是自带炫彩选择框的，我看到mod里面有添加炫彩选择框的函数，以为mod里的炫彩选择框不需要开光影就能用。 任务书里的提示框指的是任务书里面的物品的提示框，还是原版的，并没有替换成mod里的材质，如下图，其实图里面一些深色字体显示效果确实不太好，所以确实是没办法改这个提示框材质是吗 ![4d4bd9ee0fcc2cec49c894d92cb2bc36](https://private-user-images.githubusercontent.com/89056680/395769380-88617b97-51cc-4541-b620-7c89d092c386.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNjkzODUsIm5iZiI6MTczNDE2OTA4NSwicGF0aCI6Ii84OTA1NjY4MC8zOTU3NjkzODAtODg2MTdiOTctNTFjYy00NTQxLWI2MjAtN2M4OWQwOTJjMzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDA5MzgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2OTI0OWVkMzUxNDhkZDhhM2IwMzk2NTQyYjA1NGI2YzkwY2M0YjIxMzlmYTEyNTBkZDQ5NWY5MDM4MTJhY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-rnEefmrrwBtB5POrFcbCaofDtmYnp5cqW738ARjE2U)

任务书里应该是有自己独一份的材质所以不会被改变。
我的目的已经达到了，所以不打算继续找它的材质，您可以自己试着找一找。

另外，我很喜欢您的字体，能告诉我是哪个字体以及如何修改为图中的字体吗？

**Comment by haobawobufu** [comment]
字体是我自己修改的，中文字体是悠哉字体，英文字体（ascii）是Yomogi（等宽字体），我用了字体修改软件把两个字体合一了（因为悠哉自带的英文字体不等宽，在任务书里提示框显示会出问题）

**Comment by CanntReport** [comment]
> 字体是我自己修改的，中文字体是悠哉字体，英文字体（ascii）是Yomogi（等宽字体），我用了字体修改软件把两个字体合一了（因为悠哉自带的英文字体不等宽，在任务书里提示框显示会出问题）

感谢分享，祝您愉快
